# .github/workflows/staging.yml
#
# GitHub Action for Serverless NextJS staging environment
#
name: Deploy prod-steedos-website

on:
  push:
    tags: # Deploy tag (e.g. v1.0) to production
      - 'v**'
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: prod
    env:
      STEEDOS_SERVER_API_KEY: ${{ secrets.STEEDOS_SERVER_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_DEPLOYMENT_URL: https://www.steedos.cn
      NEXT_PUBLIC_STEEDOS_SERVER_ROOT_URL: https://console.steedos.cn
      NEXT_STATIC_PROPS_REVALIDATE: 3600
    steps:
      - uses: actions/checkout@v2

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-east-1

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://steedos-serverless-state-bucket/steedos.com.cn/prod/.serverless .serverless --delete  --region ap-east-1

      - uses: canastro/copy-file-action@master
        with:
          source: 'serverless-prod.yml'
          target: 'serverless.yml'

      - name: Use Node.js '14'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: "yarn"

      - run: yarn --frozen-lockfile

      - name: Serverless AWS authentication
        run: npx serverless@2.72.2 --component=serverless-next config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to AWS
        run: npx serverless@2.72.2

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://steedos-serverless-state-bucket/steedos.com.cn/prod/.serverless --delete  --region ap-east-1